name: Deploy GitHub Contributions Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Roda automaticamente todos os dias à meia-noite (UTC)

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Verificar o código
    - name: Check out code
      uses: actions/checkout@v4

    # Passo 2: Configurar o Bun (se você estiver usando Bun como gerenciador de pacotes)
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1

    # Passo 3: Instalar dependências
    - name: Install dependencies
      run: bun install --frozen-lockfile

    # Passo 4: Gerar o gráfico de contribuições
    - name: Generate GitHub contributions snake
      run: |
        npm run generate-snake --github_user_name=renancvitor
        # Certifique-se de ter um script ou comando para gerar o gráfico com base no seu código

    # Passo 5: Publicar no GitHub Pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4.1.0
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Passo 6: Verificar arquivos gerados
    - name: Ensure files were generated
      run: |
        ls dist
        test -f dist/github-contribution-grid-snake.svg
        test -f dist/github-contribution-grid-snake-dark.svg
